### ISSUE TITLE
SimpleTacticsExample not working

### ISSUE THREAD

**Issue by FaKeller** [FaKeller/palladio-lqns-headless#1]
Running the SimpleTacticsExample with the `RunLQNS` runner is currently not possible, even though the example works seamlessly in the Palladio Bench.

The error occurs in the `transform()` method of the `Pcm2LqnStrategy` and is related to properly referencing certain parts of the model.

**Hint:** A key difference between the [headless launch configuration](https://github.com/FaKeller/palladio-lqns-headless/blob/fd43c1ec38774bf813282a50900fddf378edc9a8/src/main/java/de/fabiankeller/palladio/RunLQNS.java#L111-L129) and the [actual run configuration](https://svnserver.informatik.kit.edu/i43/svn/code/Palladio/Examples/SimpleHeuristicsExample_Example/run%20configs/Simple%20Tactics%20Example%20LQN.launch) is how the `usageFile` and `allocationFile` are referenced. While the actual launch configuration uses platform paths (i.e. `platform:/resource/Simple Tactics Example/default.usagemodel`) the headless approach uses direct file paths (i.e. `C:\...\default.usagemodel`). Maybe this could be related to the issue?

The RunLQNS produces the following output:

	C:\Applications\Java\jdk1.8.0_77\bin\java -Didea.launcher.port=7533 -Didea.launcher.bin.path=C:\Applications\IntelliJ2016\bin -classpath C:\Users\Fabian\AppData\Local\Temp\classpath1.jar -Dfile.encoding=UTF-8 com.intellij.rt.execution.application.AppMain de.fabiankeller.palladio.RunLQNS
	Mai 24, 2016 11:12:16 AM de.fabiankeller.palladio.RunLQNS main
	INFORMATION: Loading runner configuration from: src/main/resources/config.properties
	Mai 24, 2016 11:12:16 AM de.fabiankeller.palladio.RunLQNS run
	INFORMATION: Launching LQNS headless
	Mai 24, 2016 11:12:16 AM de.fabiankeller.palladio.RunLQNS initEmfFactories
	INFORMATION: Initialized EMF factories
	Mai 24, 2016 11:12:16 AM de.fabiankeller.palladio.RunLQNS initEmfFactories
	INFORMATION: Initialized resource factories
	Mai 24, 2016 11:12:17 AM de.fabiankeller.palladio.RunLQNS run
	INFORMATION: Created PCM Instance
	Mai 24, 2016 11:12:17 AM de.fabiankeller.palladio.RunLQNS run
	INFORMATION: Created workflow config
	Mai 24, 2016 11:12:17 AM de.fabiankeller.palladio.RunLQNS run
	INFORMATION: Created PCM2LQN strategy
	0    [main] WARN  sformations.pcm2lqn.Pcm2LqnStrategy  - Finished DSolver:		87 ms
	101  [main] WARN  ons.pcm2lqn.ResourceEnvironment2Lqn  - Unknown scheduling strategy _nKJwMSGPEeaSOKQccz2lUQ, using PROCESSOR_SHARING for aName of server Server1 (id: _g7HJEC6MEd-Jla2o7wkBzQ)
	106  [main] WARN  ons.pcm2lqn.ResourceEnvironment2Lqn  - Unknown scheduling strategy _nKKXQiGPEeaSOKQccz2lUQ, using PROCESSOR_SHARING for aName of server server2 (id: _h3wXgC6MEd-Jla2o7wkBzQ)
	107  [main] WARN  ons.pcm2lqn.ResourceEnvironment2Lqn  - Unknown scheduling strategy _nKKXRiGPEeaSOKQccz2lUQ, using PROCESSOR_SHARING for aName of server Server3 (id: _vxqJwS6QEd-pNfzbJsur0g)
	Exception in thread "main" java.lang.RuntimeException: Could not find org.palladiosimulator.pcm.resourceenvironment.ProcessingResourceSpecificationof type aName(id:_nJZiQCGPEeaSOKQccz2lUQ) adressed by resource demand of action action (_vGuakC6JEd-Jla2o7wkBzQ). Check your model that the required resources are available on the server.
		at org.palladiosimulator.solver.transformations.pcm2lqn.Rdseff2Lqn.getProcessorName(Rdseff2Lqn.java:590)
		at org.palladiosimulator.solver.transformations.pcm2lqn.Rdseff2Lqn.caseInternalAction(Rdseff2Lqn.java:527)
		at org.palladiosimulator.solver.transformations.pcm2lqn.Rdseff2Lqn.caseInternalAction(Rdseff2Lqn.java:1)
		at org.palladiosimulator.pcm.seff.util.SeffSwitch.doSwitch(SeffSwitch.java:646)
		at org.palladiosimulator.pcm.seff.util.SeffSwitch.doSwitch(SeffSwitch.java:103)
		at org.palladiosimulator.pcm.seff.util.SeffSwitch.doSwitch(SeffSwitch.java:90)
		at org.palladiosimulator.solver.transformations.pcm2lqn.Rdseff2Lqn.caseStartAction(Rdseff2Lqn.java:280)
		at org.palladiosimulator.solver.transformations.pcm2lqn.Rdseff2Lqn.caseStartAction(Rdseff2Lqn.java:1)
		at org.palladiosimulator.pcm.seff.util.SeffSwitch.doSwitch(SeffSwitch.java:277)
		at org.palladiosimulator.pcm.seff.util.SeffSwitch.doSwitch(SeffSwitch.java:103)
		at org.palladiosimulator.pcm.seff.util.SeffSwitch.doSwitch(SeffSwitch.java:90)
		at org.palladiosimulator.solver.transformations.pcm2lqn.Rdseff2Lqn.caseResourceDemandingSEFF(Rdseff2Lqn.java:177)
		at org.palladiosimulator.solver.transformations.pcm2lqn.Rdseff2Lqn.caseResourceDemandingSEFF(Rdseff2Lqn.java:1)
		at org.palladiosimulator.pcm.seff.util.SeffSwitch.doSwitch(SeffSwitch.java:308)
		at org.palladiosimulator.pcm.seff.util.SeffSwitch.doSwitch(SeffSwitch.java:103)
		at org.palladiosimulator.pcm.seff.util.SeffSwitch.doSwitch(SeffSwitch.java:90)
		at org.palladiosimulator.solver.transformations.pcm2lqn.UsageModel2Lqn.createCallActivity(UsageModel2Lqn.java:272)
		at org.palladiosimulator.solver.transformations.pcm2lqn.UsageModel2Lqn.caseEntryLevelSystemCall(UsageModel2Lqn.java:249)
		at org.palladiosimulator.solver.transformations.pcm2lqn.UsageModel2Lqn.caseEntryLevelSystemCall(UsageModel2Lqn.java:1)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:154)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:90)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:77)
		at org.palladiosimulator.solver.transformations.pcm2lqn.UsageModel2Lqn.caseStart(UsageModel2Lqn.java:223)
		at org.palladiosimulator.solver.transformations.pcm2lqn.UsageModel2Lqn.caseStart(UsageModel2Lqn.java:1)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:276)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:90)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:77)
		at org.palladiosimulator.solver.transformations.pcm2lqn.UsageModel2Lqn.caseScenarioBehaviour(UsageModel2Lqn.java:201)
		at org.palladiosimulator.solver.transformations.pcm2lqn.UsageModel2Lqn.caseScenarioBehaviour(UsageModel2Lqn.java:1)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:191)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:90)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:77)
	118  [main] ERROR nsformations.pcm2lqn.UsageModel2Lqn  - Error while visiting RDSEFF
		at org.palladiosimulator.solver.transformations.pcm2lqn.UsageModel2Lqn.caseUsageScenario(UsageModel2Lqn.java:100)
		at org.palladiosimulator.solver.transformations.pcm2lqn.UsageModel2Lqn.caseUsageScenario(UsageModel2Lqn.java:1)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:121)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:90)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:77)
		at org.palladiosimulator.solver.transformations.pcm2lqn.UsageModel2Lqn.caseUsageModel(UsageModel2Lqn.java:92)
		at org.palladiosimulator.solver.transformations.pcm2lqn.UsageModel2Lqn.caseUsageModel(UsageModel2Lqn.java:1)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:146)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:90)
		at org.palladiosimulator.pcm.usagemodel.util.UsagemodelSwitch.doSwitch(UsagemodelSwitch.java:77)
		at org.palladiosimulator.solver.transformations.pcm2lqn.Pcm2LqnStrategy.runPcm2Lqn(Pcm2LqnStrategy.java:447)
		at org.palladiosimulator.solver.transformations.pcm2lqn.Pcm2LqnStrategy.transform(Pcm2LqnStrategy.java:424)
		at de.fabiankeller.palladio.RunLQNS.run(RunLQNS.java:98)
		at de.fabiankeller.palladio.RunLQNS.main(RunLQNS.java:75)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

	Process finished with exit code 1

**Comment by FaKeller** [comment]
Root cause of the issue was that `pathmap://PCM_MODELS/` references between model files could not be resolved, as the extension point of Eclipse defining the path mapping is not loaded by the runner.

The issue was resolved by [intercepting the URI normalization](https://github.com/FaKeller/palladio-lqns-headless/blob/6df53084974b9b93475681a6ffa8baf61cd1544b/src/main/java/de/fabiankeller/palladio/RunLQNS.java#L113-L124) and overriding the default [static `ExtensibleURIConverterImpl` with the interceptor](https://github.com/FaKeller/palladio-lqns-headless/blob/6df53084974b9b93475681a6ffa8baf61cd1544b/src/main/java/de/fabiankeller/palladio/RunLQNS.java#L127-L136) in place.

---

Palladio has another URI mapping in place, which might also be needed for future models:

`plugin.xml` file in `Palladio\Core\trunk\PCM\org.palladiosimulator.pcm.resources\plugin.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?eclipse version="3.2"?>
<plugin>
  <extension
     point="org.eclipse.emf.ecore.uri_mapping">
    <mapping
       source="pathmap://PCM_MODELS/"
       target="platform:/plugin/org.palladiosimulator.pcm.resources/defaultModels/">
    </mapping>
    <mapping
       source="pathmap://PCM_TRANSFORMATIONS/EVENTS/"
       target="platform:/plugin/org.palladiosimulator.pcm.resources/transformations/events/">
    </mapping>
  </extension>
</plugin>

```

**Comment by alejandrorago** [comment]
Hi Fabian!
A more elegant way of fixing the problem is to use URI convertion mappings in a static context:
```
static {
	Path currentPath = Paths.get("").toAbsolutePath();
	Path workspacePath = currentPath.getParent();
	String uriPath = workspacePath.normalize().toString();
	//URI platformURI = URI.createPlatformPluginURI("org.palladiosimulator.pcm.resources", true).appendSegment("defaultModels").appendSegment("");
	URI physicalURI = URI.createFileURI(uriPath).appendSegment("PCM").appendSegment("org.palladiosimulator.pcm.resources").appendSegment("defaultModels").appendSegment("");
	URI pcmModels = URI.createURI("pathmap://PCM_MODELS/");
	URIConverter.URI_MAP.put(pcmModels, physicalURI);
}
```
I ran into the same problem yesterday ;)

Cheers!

**Comment by FaKleiser** [comment]
Hi Alejandro,

thanks for sharing the snippet, I openend a new issue to improve the current implementation with your snippet.

Cheers,
Fabian
